'use strict';
const stages=[
{title:'Start with a complete application.',description:'Capture the applicant, lending product, branch and partner details in a shared file, with clear ownership from the start.',items:['Lead and applicant intake','Product and branch assignment','Document collection']},
{title:'Bring the evidence into view.',description:'Structure identity and document checks, then bring bureau and financial inputs into the case before underwriting.',items:['Identity and document verification','Bureau and bank statement inputs','Field or back-office verification']},
{title:'Connect policy to the credit review.',description:'Evaluate eligibility, scorecards and deviations alongside risk signals. Give authorised reviewers the reasons and context behind a recommendation.',items:['AI BRE policy evaluation','Credit queries and review conditions','Manual review and fallback paths']},
{title:'Make the approved terms clear.',description:'Prepare the offer and supporting documents with approval conditions and sanction evidence attached to the application.',items:['Offer, terms and conditions','Sanction letters, KFS and MITC','Approval authority and evidence']},
{title:'Check readiness before disbursement.',description:'Bring agreements, mandates and account checks together in the operations checklist, with final maker-checker control.',items:['Agreement, mandate and penny-drop checks','Final maker-checker approval','Disbursement action and audit trail']}
];
document.querySelectorAll('[data-step]').forEach(button=>button.addEventListener('click',()=>{const index=Number(button.dataset.step),stage=stages[index];document.querySelectorAll('[data-step]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button));});document.querySelector('#stage-count').textContent=String(index+1).padStart(2,'0')+' / 05';document.querySelector('#stage-title').textContent=stage.title;document.querySelector('#stage-description').textContent=stage.description;document.querySelector('#stage-items').replaceChildren(...stage.items.map(item=>{const li=document.createElement('li');li.textContent=item;return li;}));}));
document.querySelector('#demo-form').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;const data=new FormData(form);const subject='Finhashy demo enquiry — '+data.get('company');const body=['Hello Finhashy team,','','I would like to request a product demo.','','Name: '+data.get('name'),'Work email: '+data.get('email'),'Company: '+data.get('company'),'Interested in: '+data.get('interest'),'','Please contact me to arrange a suitable time.'].join('\r\n');document.querySelector('#form-status').hidden=false;window.location.href='mailto:info@finhashy.com?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);});
const toggle=document.querySelector('.menu-toggle');
const navigation=document.querySelector('#navigation');
function closeNavigation(){navigation.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Open navigation');}
toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';navigation.classList.toggle('open',open);toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close navigation':'Open navigation');});
navigation.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeNavigation));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&toggle.getAttribute('aria-expanded')==='true'){closeNavigation();toggle.focus();}});
document.querySelector('#year').textContent=new Date().getFullYear();
const showcase=document.querySelector('#showcase-content');
const pipeline=showcase.innerHTML;
const decision='<div class="case-top"><span>Decision · FH-DEMO</span><span class="pill amber">Manual review</span></div><div class="case-title"><div class="avatar borrower">◇</div><div><b>Policy evaluation</b><small>Illustrative decision · not a lending offer</small></div></div><div class="check-list"><div><span class="check">✓</span><span>Eligibility rules</span><span class="status">Passed</span></div><div><span class="check">✓</span><span>Bureau policy check</span><span class="status">Passed</span></div><div><span class="pending">◷</span><span>Income evidence</span><span class="muted">Review required</span></div></div><div class="case-note"><span class="note-icon">◇</span><div><b>Reason: income verification pending</b><small>Route to the credit team before approval.</small></div></div><div class="case-fields"><div><small>Decision ownership</small><b>Authorised reviewer</b></div><div><small>Evidence</small><b>Audit history</b></div></div>';
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button));});showcase.innerHTML=button.dataset.view==='pipeline'?pipeline:decision;}));
